name: format-check

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: x64
      - uses: psf/black@23.1.0
        with:
          options: "--check"
          src: "./ulc_mm_package"
